name: 💬 General Discussion
description: Start a general conversation about the project
title: ""
labels: ["general"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome! This is a space for general discussion about the Notify CLI project.

  - type: textarea
    attributes:
      label: What's on your mind?
      description: Share your thoughts, ideas, or start a conversation
      placeholder: "What would you like to discuss?"
      validations:
        required: true
