name: ❓ Question
description: Ask a question about the project
title: "[QUESTION] "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! We'll do our best to help you out.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: "Ask your question here..."
    validations:
      required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - How to use the tool
        - Installation help
        - Configuration help
        - Troubleshooting
        - Best practices
        - General inquiry
        - Other
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your system environment (if relevant)
      placeholder: "OS: macOS, Node.js: 18.17.0, Notify CLI: 1.0.0"

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information
      placeholder: "Describe what you're trying to accomplish or any relevant background..."

  - type: textarea
    id: what-tried
    attributes:
      label: What Have You Tried?
      description: Describe any steps you've already taken to solve this
      placeholder: "List any steps you've already taken, commands you've run, or resources you've checked..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: "Any additional information that might be helpful..."
